import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { EpisodeDoc, EventDoc, OperationContext, Store } from "me0-core";

export function defaultPiSessionsDir(): string {
  return join(homedir(), ".pi", "agent", "sessions");
}

/**
 * Detect `~/.pi/agent/` and install the me0 pi extension as a wrapper that
 * re-exports `extensions/pi/me0.ts` from this checkout/install.
 * Returns human-readable status lines for `me0 init` to print.
 */
export function wirePi(): string[] {
  const piDir = join(homedir(), ".pi", "agent");
  if (!existsSync(piDir)) return ["pi not detected (~/.pi/agent missing) — skipped"];
  const extDir = join(piDir, "extensions");
  mkdirSync(extDir, { recursive: true });
  const target = join(extDir, "me0.ts");
  if (existsSync(target) && readFileSync(target, "utf-8").includes("me0")) {
    return [`pi already wired: ${target}`];
  }
  const source = join(dirname(new URL(import.meta.url).pathname), "../../../extensions/pi/me0.ts");
  writeFileSync(
    target,
    `// me0 pi extension wrapper — generated by \`me0 init\`\nexport { default } from ${JSON.stringify(source)};\n`,
  );
  return [
    `pi wired: ${target}`,
    "pi: run `me0 import-pi` to backfill past pi sessions (~/.pi/agent/sessions)",
  ];
}

export interface PiImportStats {
  files: number;
  imported: number;
  skipped: number;
  events: number;
}

interface PiHeader {
  id: string;
  timestamp: string | null;
  cwd: string | null;
}

type Json = Record<string, unknown>;

function asObj(v: unknown): Json | null {
  return v && typeof v === "object" && !Array.isArray(v) ? (v as Json) : null;
}

function textOf(content: unknown): string {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content
      .map((c) => {
        const o = asObj(c);
        return o && o.type === "text" && typeof o.text === "string" ? o.text : "";
      })
      .filter(Boolean)
      .join("\n");
  }
  return "";
}

function cap(s: string, n = 500): string {
  return s.length > n ? `${s.slice(0, n)}…` : s;
}

/** Session entries may be raw messages or wrapped as `{type:"message", message}`. */
function messageOf(entry: Json): Json | null {
  if (entry.type === "message") {
    const inner = asObj(entry.message);
    if (inner) return inner;
  }
  return typeof entry.role === "string" ? entry : null;
}

function parseLines(raw: string): Json[] {
  const out: Json[] = [];
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try {
      const obj = asObj(JSON.parse(line));
      if (obj) out.push(obj);
    } catch {
      // tolerate malformed lines — backfill is best-effort and deterministic
    }
  }
  return out;
}

function eventsForFile(
  header: PiHeader,
  entries: Json[],
): {
  events: Omit<EventDoc, "episode_id">[];
  endedAt: string | null;
  title: string | null;
  model: string | null;
} {
  const events: Omit<EventDoc, "episode_id">[] = [];
  let endedAt: string | null = header.timestamp;
  let title: string | null = null;
  let model: string | null = null;

  const resultOk = new Map<string, boolean>();
  for (const entry of entries) {
    const msg = messageOf(entry);
    if (msg?.role === "toolResult" && typeof msg.toolCallId === "string") {
      resultOk.set(msg.toolCallId, msg.isError !== true);
    }
  }

  for (const entry of entries) {
    const ts =
      (typeof entry.timestamp === "string" ? entry.timestamp : null) ??
      endedAt ??
      new Date(0).toISOString();
    endedAt = ts;
    const msg = messageOf(entry);
    if (!msg) continue;
    const role = msg.role;
    if (role === "user") {
      const text = textOf(msg.content);
      if (!title && text) title = cap(text, 80);
      events.push({ ts, type: "prompt", tool: null, ok: null, payload: { text: cap(text) } });
    } else if (role === "assistant") {
      if (typeof msg.model === "string") model = msg.model;
      const text = textOf(msg.content);
      if (text) {
        events.push({ ts, type: "response", tool: null, ok: null, payload: { text: cap(text) } });
      }
      if (Array.isArray(msg.content)) {
        for (const c of msg.content) {
          const o = asObj(c);
          if (o?.type !== "toolCall" || typeof o.name !== "string") continue;
          const callId = typeof o.id === "string" ? o.id : null;
          events.push({
            ts,
            type: "tool_call",
            tool: o.name,
            ok: callId !== null ? (resultOk.get(callId) ?? null) : null,
            payload: { arguments: cap(JSON.stringify(o.arguments ?? {})) },
          });
        }
      }
    } else if (role === "bashExecution") {
      events.push({
        ts,
        type: "command",
        tool: "bash",
        ok: typeof msg.exitCode === "number" ? msg.exitCode === 0 : null,
        payload: { command: cap(String(msg.command ?? "")) },
      });
    }
  }
  return { events, endedAt, title, model };
}

/**
 * Deterministic, idempotent backfill of pi JSONL session trees
 * (all `.jsonl` files under `~/.pi/agent/sessions/`) into episodes + events.
 * Idempotency key: the session file's header id → `ep_pi_<id>`.
 */
export async function importPiSessions(
  db: Store["db"],
  ctx: OperationContext,
  dir: string,
): Promise<PiImportStats> {
  const stats: PiImportStats = { files: 0, imported: 0, skipped: 0, events: 0 };
  const files = (readdirSync(dir, { recursive: true }) as string[]).filter((f) =>
    f.endsWith(".jsonl"),
  );

  for (const rel of files) {
    stats.files++;
    const entries = parseLines(readFileSync(join(dir, rel), "utf-8"));
    const header = entries.find((e) => e.type === "session" && typeof e.id === "string");
    if (!header) continue;
    const h: PiHeader = {
      id: header.id as string,
      timestamp: typeof header.timestamp === "string" ? header.timestamp : null,
      cwd: typeof header.cwd === "string" ? header.cwd : null,
    };
    const episodeId = `ep_pi_${h.id}`;
    const existing = await db
      .collection<EpisodeDoc>("episodes")
      .findOne({ user_id: ctx.user_id, episode_id: episodeId });
    if (existing) {
      stats.skipped++;
      continue;
    }

    const { events, endedAt, title, model } = eventsForFile(
      h,
      entries.filter((e) => e !== header),
    );
    const startedAt = h.timestamp ?? endedAt ?? new Date(0).toISOString();
    const promptCount = events.filter((e) => e.type === "prompt").length;
    const toolCallCount = events.filter((e) => e.type === "tool_call").length;
    const episode: EpisodeDoc = {
      user_id: ctx.user_id,
      episode_id: episodeId,
      harness: "pi",
      agent: { name: "pi", model },
      project: null,
      repo: { remote: null, branch: null, cwd: h.cwd },
      started_at: startedAt,
      ended_at: endedAt ?? startedAt,
      status: "ended",
      title,
      summary: `imported pi session ${h.id}: ${promptCount} prompts, ${toolCallCount} tool calls`,
      outcome: { success: null, artifacts: [], commits: [] },
      handoff: null,
      tags: ["pi-import"],
    };
    // Events first, episode last: an episode doc's presence implies its event
    // stream landed. Events carry no user_id, so the stream is shared across
    // users; only rewrite it when no episode (for any user) references it yet
    // — that repairs interrupted runs without destroying a stream another
    // user already imported.
    const streamOwned = await db
      .collection<EpisodeDoc>("episodes")
      .findOne({ episode_id: episodeId }, { projection: { _id: 1 } });
    if (!streamOwned) {
      await db.collection<EventDoc>("events").deleteMany({ episode_id: episodeId });
      if (events.length > 0) {
        await db
          .collection<EventDoc>("events")
          .insertMany(events.map((e) => ({ ...e, episode_id: episodeId })));
      }
      stats.events += events.length;
    }
    await db.collection<EpisodeDoc>("episodes").insertOne(episode);
    stats.imported++;
  }
  return stats;
}
